#!/bin/bash
clear
rm -f Chinese-LANG-Pack.tar.xz
mkdir ~/drive_e &>/dev/null
mkdir $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/mnt/drive_e &>/dev/null
echo -e " Box64Droid中文化补丁..." 
echo -e " 本补丁除中文环境外，还会包含一些额外的便捷功能"
if [ -f "$PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Chinese-LANG-Pack/SimSun.ttc" ]; then
	echo -e " 检测到OPT目录已存在补丁文件，不再重复下载中文化补丁"
elif [ -f /sdcard/download/Chinese-LANG-Pack.tar.xz ]&&[ 811cad9d4e6406db3b004a3229cb1bb2 == $(md5sum /sdcard/download/Chinese-LANG-Pack.tar.xz | cut -d " " -f1) ]
then
	echo " 检测存在本地文件使用，使用本地文件进行安装"
	cp -f /sdcard/download/Chinese-LANG-Pack.tar.xz Chinese-LANG-Pack.tar.xz 
	tar -xf Chinese-LANG-Pack.tar.xz
	rm -f Chinese-LANG-Pack.tar.xz
	echo -e " 移动补丁到ubuntu目录"
	rm -rf $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Chinese-LANG-Pack
	mv -f Chinese-LANG-Pack $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/
else
	echo -e " 补丁下载中"
	wget -q --show-progress https://github.com/lsl330/Box64Droid-For-Chinese/releases/download/Chinese-LANG-Pack/Chinese-LANG-Pack.tar.xz
	echo -e " 下载完成，备份中文包到本地download文件夹"
	cp -f Chinese-LANG-Pack.tar.xz /sdcard/download/Chinese-LANG-Pack.tar.xz
	tar -xf Chinese-LANG-Pack.tar.xz
	rm -f Chinese-LANG-Pack.tar.xz
	echo -e " 移动补丁到ubuntu目录"
	rm -rf $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Chinese-LANG-Pack
	mv -f Chinese-LANG-Pack $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/
fi
if [ -f "$PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Chinese-LANG-Pack/SimSun.ttc" ]; then
	echo -e " 检测到OPT目录已存在补丁文件，不再重复下载中文化补丁"
else
	echo -e " 补丁下载中"
	wget -q --show-progress https://github.com/lsl330/Box64Droid-For-Chinese/releases/download/Chinese-LANG-Pack/Chinese-LANG-Pack.tar.xz
	tar -xf Chinese-LANG-Pack.tar.xz
	rm -f Chinese-LANG-Pack.tar.xz
	echo -e " 移动补丁到ubuntu目录"
	rm -rf $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Chinese-LANG-Pack
	mv -f Chinese-LANG-Pack $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/
fi
echo -e " 复制字体文件"
cp -f $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Chinese-LANG-Pack/SimSun.ttc $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/wine/share/wine/fonts/SimSun.ttc
cp -f $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Chinese-LANG-Pack/PMingLiU-TW.ttf $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/wine/share/wine/fonts/PMingLiU-TW.ttf
cp -f $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Chinese-LANG-Pack/locale-archive-cn $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/usr/lib/locale/locale-archive
echo -e " 替换Box64Droid.conf为中文环境"
sed -i 's/[a-z][a-z]_[[A-Z][A-Z].UTF-8/zh_CN.UTF-8/g' $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Box64Droid.conf
if [ -f /sdcard/Box64Droid/Box64Droid.conf ]; then
	sed -i 's/[a-z][a-z]_[[A-Z][A-Z].UTF-8/zh_CN.UTF-8/g' /sdcard/Box64Droid/Box64Droid.conf
fi
echo -e " 替换TFM为中文版"
cp -f $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Chinese-LANG-Pack/TFM.exe $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/TFM.exe
echo -e " 起点位置添加快捷启动项"
cp -rf $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Chinese-LANG-Pack/Shortcuts $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt
cp -rf $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Shortcuts/*  "$PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/root/.wine/drive_c/ProgramData/Microsoft/Windows/Start Menu"
if [ -f "$PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever" ]; then
	if cat $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever |grep 复制 > /dev/null;then
		echo -e " changewinever已更新，无需替换"
	else
		echo -e " 修改changewinever，更换wine版本后会自动设置中文"
		cd=$(awk '/WINEDLLOVERRIDES/{print NR}' $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever|head -n 1)
		if [ $cd -gt 0 ]; then
			sed -i "$cd a cp -f /opt/Chinese-LANG-Pack/locale-archive-cn /usr/lib/locale/locale-archive" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			sed -i "$cd a cp -f /opt/Chinese-LANG-Pack/PMingLiU-TW.ttf /opt/wine/share/wine/fonts/PMingLiU-TW.ttf" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			sed -i "$cd a cp -f /opt/Chinese-LANG-Pack/SimSun.ttc /opt/wine/share/wine/fonts/SimSun.ttc" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			sed -i "$cd a echo -e "复制字体文件"" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
		fi
	fi
	if cat $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever |grep 安装 > /dev/null;then
		echo -e " 更新wine版本时，若download/wineversion文件夹中有离线文件，则使用离线文件进行更新"
	else
		echo -e " 修改changewinever，下载wine版本时会自动备份一份到download/wineversion文件夹"
		wa=$(awk '/read build/{print NR}' $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever|head -n 1)
		if [ $wa -gt 0 ]; then
			sed -i "$wa a fi" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			sed -i "$wa a mkdir /sdcard/Download/wineversion" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			sed -i "$wa a if [ ! -d "/sdcard/Download/wineversion" ]; then" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
		fi
		wb=$(awk '/amd64.tar.xz/{print NR}' $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever|head -n 1)
		if [ $wb -gt 0 ]; then
			sed -i "$wb a cp -f wine-\$ver-amd64.tar.xz /sdcard/Download/wineversion/wine-\$ver-amd64.tar.xz" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			let wb=wb+2
			sed -i "$wb a fi" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			let wb=wb-3
			sed -i "$wb i else" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			sed -i "$wb i echo "解压完成，准备安装"" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever	
			sed -i "$wb i tar -xf wine-\$ver-amd64.tar.xz" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever	
			sed -i "$wb i cp -f /sdcard/Download/wineversion/wine-\$ver-amd64.tar.xz wine-\$ver-amd64.tar.xz" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			sed -i "$wb i echo "检测到存在已下载wine文件，进行离线复制并解压"" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever	
			sed -i "$wb i if [ -f "/sdcard/Download/wineversion/wine-\$ver-amd64.tar.xz" ]; then" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever	
			sed -i "$wb i echo "检测是否存在已下载wine文件"" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
		fi
		wc=$(awk '/staging-amd64.tar.xz/{print NR}' $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever|head -n 1)
		if [ $wc -gt 0 ]; then
			sed -i "$wc a cp -f wine-\$ver-staging-amd64.tar.xz /sdcard/Download/wineversion/wine-\$ver-staging-amd64.tar.xz" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			let wc=wc+2
			sed -i "$wc a fi" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			let wc=wc-3
			sed -i "$wc i else" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			sed -i "$wc i echo "解压完成，准备安装"" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever	
			sed -i "$wc i tar -xf wine-\$ver-staging-amd64.tar.xz" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever	
			sed -i "$wc i cp -f /sdcard/Download/wineversion/wine-\$ver-staging-amd64.tar.xz wine-\$ver-staging-amd64.tar.xz" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			sed -i "$wc i echo "检测到存在已下载wine文件，进行离线复制并解压"" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever	
			sed -i "$wc i if [ -f "/sdcard/Download/wineversion/wine-\$ver-staging-amd64.tar.xz" ]; then" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever	
			sed -i "$wc i echo "检测是否存在已下载wine文件"" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			fi

		wd=$(awk '/staging-tkg-amd64.tar.xz/{print NR}' $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever|head -n 1)
		if [ $wd -gt 0 ]; then
			sed -i "$wd a cp -f wine-\$ver-staging-tkg-amd64.tar.xz /sdcard/Download/wineversion/wine-\$ver-staging-tkg-amd64.tar.xz" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			let wd=wd+2
			sed -i "$wd a fi" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			let wd=wd-3
			sed -i "$wd i else" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			sed -i "$wd i echo "解压完成，准备安装"" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever	
			sed -i "$wd i tar -xf wine-\$ver-staging-tkg-amd64.tar.xz" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			sed -i "$wd i cp -f /sdcard/Download/wineversion/wine-\$ver-staging-tkg-amd64.tar.xz wine-\$ver-staging-tkg-amd64.tar.xz" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			sed -i "$wd i echo "检测到存在已下载wine文件，进行离线复制并解压"" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever	
			sed -i "$wd i if [ -f "/sdcard/Download/wineversion/wine-\$ver-staging-tkg-amd64.tar.xz" ]; then" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever	
			sed -i "$wd i echo "检测是否存在已下载wine文件"" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
		fi
		
		wp=$(cat $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever |grep -oE 'wine-proton-[0-9a-zA-Z.-]+-amd64'|head -n 1)
		we=$(awk '/wine-proton/{print NR}' $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever|head -n 1)
		if [ $we -gt 0 ]; then
			sed -i "$we a cp -f $wp.tar.xz /sdcard/Download/wineversion/\$wp.tar.xz" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			let we=we+2
			sed -i "$we a fi" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			let we=we-3
			sed -i "$we i else" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			sed -i "$we i echo "解压完成，准备安装"" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever	
			sed -i "$we i tar -xf \$wp.tar.xz" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever	
			sed -i "$we i cp -f /sdcard/Download/wineversion/\$wp.tar.xz \$wp.tar.xz" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			sed -i "$we i echo "检测到存在已下载wine文件，进行离线复制并解压"" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever	
			sed -i "$we i if [ -f "/sdcard/Download/wineversion/\$wp.tar.xz" ]; then" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever	
			sed -i "$we i echo "检测是否存在已下载wine文件"" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			sed -i "$we i wp=$wp" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
		fi

		#ge=$(cat $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever |grep -oE 'wine-lutris-GE-Proton[0-9a-zA-Z.-]+-x86_64'|head -n 1)
		#wf=$(awk '/wine-lutris-GE-Proton/{print NR}' $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever|head -n 1)
		#if [ $wf -gt 0 ]; then
			#sed -i "$wf a cp -f $ge.tar.xz /sdcard/Download/wineversion/\$ge.tar.xz" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			#let wf=wf+2
			#sed -i "$wf a fi" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			#let wf=wf-3
			#sed -i "$wf i else" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			#sed -i "$wf i echo "解压完成，准备安装"" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever	
			#sed -i "$wf i tar -xf \$ge.tar.xz" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever	
			#sed -i "$wf i cp -f /sdcard/Download/wineversion/\$ge.tar.xz \$ge.tar.xz" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			#sed -i "$wf i echo "检测到存在已下载wine文件，进行离线复制并解压"" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever	
			#sed -i "$wf i if [ -f "/sdcard/Download/wineversion/\$ge.tar.xz" ]; then" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever	
			#sed -i "$wf i echo "检测是否存在已下载wine文件"" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
			#sed -i "$wf i ge=$ge" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/changewinever
		#fi
		echo -e " changewinever修改完成，更新wine时先检测download/wineversion文件夹有无离线文件，有则使用离线文件进行更新"
	fi
fi
if cat $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/etc/security/limits.conf |grep proot > /dev/null
then
	echo -e " 已打proot突破限制补丁"
else
	echo -e " 备份proot限制文件"
	cp -f $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/etc/security/limits.conf $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/etc/security/limits.conf.bakup
	echo -e " 突破proot连接数限制"
	echo -e >> $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/etc/security/limits.conf
	echo "#unlock proot limit" >> $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/etc/security/limits.conf
	echo "root - nofile 24576" >> $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/etc/security/limits.conf
	echo "root - memlock 36784" >> $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/etc/security/limits.conf
	echo "root - sigpending 36784" >> $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/etc/security/limits.conf
fi
echo -e " 下载语言环境切换文件"
wget https://raw.githubusercontent.com/lsl330/Box64Droid-For-Chinese/main/lang &>/dev/null
chmod +x lang
mv -f lang $PREFIX/bin/lang
echo -e " 配置语言环境切换文件，以后在termux上运行lang即可切换语言环境"
if [ -f "$PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/root/.wine/dosdevices/d:/run.bat" ]; then
	echo -e " d盘已有启动文件，无需替换"
else
	echo -e " 下载run.bat到D盘根目录，快捷启动将优先使用run.bat启动"
	echo -e " 若需修改run.bat文件，保存时，记得将编码调整为ansi"
	wget https://raw.githubusercontent.com/lsl330/Box64Droid-For-Chinese/main/run.bat &>/dev/null
	mv -f run.bat $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/root/.wine/dosdevices/d:/run.bat
fi	

if [ -f "$PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/start" ]; then
	if cat $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/start |grep quickstart > /dev/null;then
		echo -e " start已更新，无需更改"
	else
		echo -e " 修改start文件"
		ca=$(awk '/read choice/{print NR}' $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/start|head -n 1)
		if [ $ca -gt 0 ]; then
			sed -i "$ca a fi" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/start
			sed -i "$ca i else" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/start
			sed -i "$ca i choice=1" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/start
			sed -i "$ca i if [ -f "/opt/quickstart" ]; then" $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/start
		fi
	fi
fi

if [ -f "$PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/start-box64" ]; then
	if cat $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/start-box64 |grep 启动 > /dev/null;then
		echo -e " start-box64已更新，无需更改"
	else
		echo -e " 修改start-box64文件"
		
		echo -e " 下载start-box64进行替换"
		wget https://raw.githubusercontent.com/lsl330/Box64Droid-For-Chinese/main/box64droid/start-box64 &>/dev/null
		mv -f start-box64 $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/Scripts/start-box64
	fi
fi
if [ -f "$PREFIX/bin/start-box64droid" ]; then
	if cat $PREFIX/bin/start-box64droid |grep drive_e > /dev/null;then
		echo -e " start-box64droid已更新，无需替换"
	else
		echo -e " 修改start-box64droid，添加E盘"
		ce=$(awk '/sdcard/{print NR}' $PREFIX/bin/start-box64droid|head -n 1)
		if [ $ce -gt 0 ]; then
			sed -i "$ce a command+=\" -b /data/data/com.termux/files/home/drive_e:/mnt/drive_e\"" $PREFIX/bin/start-box64droid
		fi
		sed -i 's/tmp:\/tmp/tmp\/.X11-unix\/:\/tmp\/.X11-unix\//g' $PREFIX/bin/start-box64droid
	fi
fi
if [ -f "$PREFIX/bin/box64droid" ]; then
	if cat $PREFIX/bin/box64droid |grep resolution > /dev/null; then
		echo -e " box64droid已更新，无需更改"
	elif cat $PREFIX/bin/box64droid |grep VirGL > /dev/null; then 
		echo -e " 修改box64droid文件，以后可用startbox-virgl和vbox进行快捷启动"
		sed -i "s/^[^#].*Empty/#&/g" $PREFIX/bin/box64droid
		sed -i "s/^[^#].*\"--start\"/#&/g" $PREFIX/bin/box64droid
		sed -i '0,/then/s/then/\#then/g' $PREFIX/bin/box64droid
		cf=$(awk '/else/{print NR}' $PREFIX/bin/box64droid|head -n 1)
		if [ $cf -gt 0 ]; then
			sed -i "$cf i curl -o install https://raw.githubusercontent.com/lsl330/Box64Droid-For-Chinese/main/box64droid/install && chmod +x install && ./install" $PREFIX/bin/box64droid
			sed -i "$cf i cd ~/" $PREFIX/bin/box64droid
			sed -i "$cf i elif [ \$1 = \"--chi\" ]; then" $PREFIX/bin/box64droid
			sed -i "$cf i curl -o install https://raw.githubusercontent.com/lsl330/Box64Droid-For-Chinese/main/box64droid/install && chmod +x install && ./install" $PREFIX/bin/box64droid
			sed -i "$cf i curl -o install https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/install && chmod +x install && ./install" $PREFIX/bin/box64droid
			sed -i "$cf i cd ~/" $PREFIX/bin/box64droid
			sed -i "$cf i elif [ \$1 = \"--cup\" ]; then" $PREFIX/bin/box64droid
		fi
		cp -f $PREFIX/bin/box64droid $PREFIX/bin/vbox
		sed -i "2irm -f \$PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/resolution" $PREFIX/bin/box64droid
		sed -i "2irm -f \$PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/quickstart" $PREFIX/bin/box64droid
		sed -i "2iecho 1>\$PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/quickstart" $PREFIX/bin/vbox
		cp -f $PREFIX/bin/box64droid $PREFIX/bin/startbox-virgl
		cp -f $PREFIX/bin/box64droid $PREFIX/bin/vbox
		echo -e " 可使用vbox --cup更新box64droid和安装中文补丁（更新box64droid时需手动选3），或vbox --chi安装中文补丁"
	elif cat $PREFIX/bin/box64droid |grep distro > /dev/null; then 
		echo -e " 修改box64droid文件，以后可用startbox和pbox进行快捷启动"
		sed -i "s/^[^#].*Empty/#&/g" $PREFIX/bin/box64droid
		sed -i "s/^[^#].*\"--start\"/#&/g" $PREFIX/bin/box64droid
		sed -i '0,/then/s/then/\#then/g' $PREFIX/bin/box64droid
		cf=$(awk '/else/{print NR}' $PREFIX/bin/box64droid|head -n 1)
		if [ $cf -gt 0 ]; then
			sed -i "$cf i curl -o install https://raw.githubusercontent.com/lsl330/Box64Droid-For-Chinese/main/box64droid/install && chmod +x install && ./install" $PREFIX/bin/box64droid
			sed -i "$cf i cd ~/" $PREFIX/bin/box64droid
			sed -i "$cf i elif [ \$1 = \"--chi\" ]; then" $PREFIX/bin/box64droid
			sed -i "$cf i curl -o install https://raw.githubusercontent.com/lsl330/Box64Droid-For-Chinese/main/box64droid/install && chmod +x install && ./install" $PREFIX/bin/box64droid
			sed -i "$cf i curl -o install https://raw.githubusercontent.com/Ilya114/Box64Droid/main/scripts/install && chmod +x install && ./install" $PREFIX/bin/box64droid
			sed -i "$cf i cd ~/" $PREFIX/bin/box64droid
			sed -i "$cf i elif [ \$1 = \"--cup\" ]; then" $PREFIX/bin/box64droid
		fi
		cp -f $PREFIX/bin/box64droid $PREFIX/bin/pbox
		sed -i "2irm -f \$PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/resolution" $PREFIX/bin/box64droid
		sed -i "2irm -f \$PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/quickstart" $PREFIX/bin/box64droid
		sed -i "2iecho 1>\$PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/opt/quickstart" $PREFIX/bin/pbox
		cp -f $PREFIX/bin/box64droid $PREFIX/bin/startbox
		echo -e " 可使用pbox --cup更新box64droid和安装中文补丁（更新box64droid时需手动选1），或pbox --chi安装中文补丁"
	else
		echo -e " 你的box64droid貌似不是proot版本，请检查后重试"
	fi
fi
echo -e " 安装完成"
rm -f install
